### ISSUE TITLE
No coder having problems running on mac

### ISSUE THREAD

**Issue by AVwebcss** [leonidessaguisagjr/webdriverdownloader#17]
Hello,

Let me start by telling that my coding journey started today.

i followed all guidance to install python and instapy on my mac.

when I try to run the script I get an error

`instagrambot av$ python3 instagrambot.pyTraceback (most recent call last): File "/Users/av/Desktop/InstagramBot/instagrambot.py", line 7, in <module> session = InstaPy(username = my_username,TypeError: __init__() got an unexpected keyword argument 'headLess_browser'

I then followed your instruction of 

filename = [name for name in filenames if os_name + bitness in name and name[-7:] == '.tar.gz' ]

Now I'm having another error

InstaPy Version: 0.6.13
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/Users/av/InstaPy"
Error, unable to determine correct filename for 64bit macos
Traceback (most recent call last):
  File "/Users/av/Desktop/InstagramBot/instabot.py", line 7, in <module>
    session = InstaPy(username=my_username,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/instapy.py", line 325, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/browser.py", line 122, in set_selenium_local_session
    driver_path = geckodriver_path or get_geckodriver()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/instapy/browser.py", line 38, in get_geckodriver
    sym_path = gdd.download_and_install()[1]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 174, in download_and_install
    filename_with_path = self.download(version,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 129, in download
    download_url = self.get_download_url(version, os_name=os_name, bitness=bitness)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/webdriverdownloader/webdriverdownloader.py", line 324, in get_download_url
    raise RuntimeError(info_message)
RuntimeError: Error, unable to determine correct filename for 64bit macos
AVs-MacBook-Pro-001:instagrambot av$ 

Can you help me please.

I set the headless_browser=True so I can run the script for multiple accounts at the same time.	

Thank you

**Comment by AVwebcss** [comment]
Hello. I don't even know how I to make questions here. Is there someone that read here?
Can someone help me please!
Tank you so much

**Comment by veldhaenchen** [comment]
you got a typo: 

> `instagrambot av$ python3 instagrambot.pyTraceback (most recent call last): File "/Users/av/Desktop/InstagramBot/instagrambot.py", line 7, in session = InstaPy(username = my_username,TypeError: **init**() got an unexpected keyword argument 'headLess_browser'

The Error says ` ....an unexpected keyword argument 'headLess_browser'`

> I set the headless_browser=True so I can run the script for multiple accounts at the same time.

here you say you have set `headless_browser=True`?
